language: node_js
node_js: node
services:
- mongodb
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: vsBOhNPfR5xgD0UP6BaLj3xjiUoyX7y9qLRDDoRKfgqHnOcgSoVhqJt57S7qAHdnVrc2bUzoT8yaoBjYSEu66kb47gnCMwXhWDnWgNOQkKMHBYIYVaHh1Dk7X5Y8UWAtyZh3gSdruZwXj1aFsy5pl372O1Fz3MxFGUpqdj5i2ZcN5ODcpodY054h26+QWJzNavxt893GFSVTLDmRfIn9PSPsuHG0003fq9QwCtMMd0CObXLObQ5p+OiXV7QoYpI2oUjAkVjS96YmbVfEjFfGRaDVceXo/GSzOyUAhrJeAu9TrCvvkRZ97lOLvi4PtNaNTgPdl+Iq37nDUP/rsHYzhsq17oLndURTBh7fLTEwnJAHYUmVC3to1mqWyVQWJQLH0JAwTIaRXWR0ELYOMNvoAyDoho2bo3K3NnjME4raHbdUilk9O2lAtlLTEeQsdw5Itd7n4rDjf+qKgXh/Dkr0jOgQvc0wsXfHaLzWgWojYkcMj3MmWQM3Qu5yEaDaSTVL7FAHMlAfETJEG3//km8u4+7ahT11tle8q3S7JWuZ2ePEp1ckgWermS7gMPoQCHEsVGn6cAFvcKOIDJX0Sz763wdTVdCpk9bff1CCx9bPsqHMkFA0ngAYqHw0IJbZMa8uidgv/gRTvhJKkoP0VtXqDuKV2zEmt7tn0Nsvgy57YrE=
  app: crossshare-server
  on:
    repo: RowdyRuffBoysINC/RRB-server
