language: node_js
node_js: node
services:
- mongodb
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: oc1X5oeJLeNSViIW9D3zIhvfMXHfM4LcuQjifYi1GTtxtZUKOXBdfx+oH8NgQau2tKO8xMsGqQykTQ/Y/UpMWWfF1d+sOqD9o8oUeNuFiHsQqza/H92PeGrmtpgb6Y9Q30EMB973xr02Vx/e/isnQIxYGsjsExLiaghvTCvcArjDd2ZyfAC9hvCZRl+VJ+HotgNJHdgXeHyKi5pIjfP7J75AOe+OnfB97hJlTBYie2S/vK2z8BngD49xPux+89TB6UWHtkdckuRF9YwOa4TtNfqQ7HxwHCEkJAzvYdi3JRTyHO+UT88oOOc3qQGAr8H2OhjWK9PiuPLTTLzBxO/fCrR6Sj4DlLb1oY+jzul9cof5VYnUMGtb8EAOegi6yq2rfca5fWMPHKPRG0arnejQcYyUysXXqdrfktMlO7wG+RNBrG9RiuKs+TI1nrJ6zgEdP1h7c1o3IF1BtRfzGg7zj6PMgMOxbTOmT9peMj86JSUFdSbGnGEtQVNOq8IhfAJvD+DDmMwKxnGYUYjV7nc0gtdc0vLSdhCVCN09I1Pd4dJzPBeJtIjTN5gUdqT9r53ocr01ZjoBdJJ8hCvXBNP8n8v01c5g/3ZgLV1w1ofVTiNJd3zYQJEy55IqAIjQJQhJ8h1r/Vn5Bm/zRZqN3HECCAV0dVkGo7t3Wg0/yK3BrOU=
  app: mysterious-garden-51929
  on:
    repo: RowdyRuffBoysINC/RRB-server
