deploy:
  provider: heroku
  api_key:
    secure: U5IDjygjvUF6oRXAOmXIn71gbXp2Oz39i/yTedXA1Df3nvgzSaUHtksoVxYLTtBF/PbKZKPk/OjE4zIfgQIDW/4B9NY5XtsFpI8w0PNOMUN96F9BN2ZgGi4PHdjs3OR8dDi0uIX/d0DsuF9XgKcooybx8YWwPq9iknNbtA0eH4d8/WahodKjMHj02hrsmOmgPxzJdDZWnttKsu0o+mHHnZ6TMeEI0eD2Dt2wEodXJOpgmaXdiZkzFoLqKdNfoRjbbu7CnGAt2fSFBwjvxmepNJeNlgr2TsaGPFkKTKp+X4rhsOxaVQJ0yCoj/W4+t5eRf7l+nDprtWsnAvcv4im3BcucOg2GVO8hvR1QxMHg+emOVG9u7jsABIPNP63gO/TZAaxSOVQxTFDabQtSOJlvDXN6ba+Rvf4V5qImoSuNcZYNc5lYtc0vCmL2zxlTEj6pbivh+6QXy63W9hPl12Hooqkp5CuREGYHs+0EzphCLAXkUOpX+MblLFQexyGTZtn+1pCfGxOt6VPbNmvcCxelLQ+UmNT9zjF/TZQdGdZU9eulJR6LqQufXjseGvNFXIDGWr1fa5qSacKs2efWLFUW5YppTIw4bpDz2NYknEuPGx1mSOGpQMohnTNrGU9LfhGf5WMIFhHi68kSlDMl+XdYrkr1eqvtTGSlE161TW9hdIU=
  app: mysterious-garden-51929
  on:
    repo: brentguistwite/RRB-server
